### ISSUE TITLE
Slacky doesn't open link within host browser (Chrome Canary)

### ISSUE THREAD

**Issue by jiabinf** [hashtag-include/slacky#5] opened 2016-05-03 08:07 UTC
Hi Trevor and Matan,

Thanks for creating Slacky! I use it heavily in my daily work.

I use Chrome and Chrome Canary two browsers in parallel on Mac [1], Slacky runs in Canary. Recently when clicking a link in Slacky, it opens system default browser Chrome instead of Canary (used to be in Canary), this is quite inconvenient.

Versions:

Slacky: 1.6 from Chrome web store
Chrome Canary:  52.0.2721.0 canary (64-bit)
OS X El Capitan: 10.11.4

Any idea how to solve this?

[1] I need two browsers because I setup Canary with proxy which bypasses Great Fire Wall, in order to browse the blocked sites, e.g. GitHub and Slack...The default browser is for unblocked sites, so when Slacky throws a GitHub link to the default browser, I have to copy the URL back to Canary manually to browse.

**Comment by SimpleAnecdote** [comment] 2016-05-03 10:33
@jiabinf The most recent version of Slacky was updated to deal with a bug related to clicking and opening links from within the Slacky app -  #4.I believe what you're experiencing might be a side-effect of this change. However, it's worth noting these "confusions" are sometimes difficult to sort through as we rely on the Chrome packaged apps framework, and having both browsers installed side-by-side can be definitely considered an "edge case". Hopefully we'll be able to solve this as well. If you manage to find relevant links from other Chrome packaged apps opening links in the wrong browser and how they fixed it - that would be helpful ;P

**Comment by trjast** [comment] 2016-05-18 01:39
@SimpleAnecdote is totally correct, before #4 links wouldn't work correctly in Chrome. Honestly I'm not sure why it even changed which browser the links are opened in, since it's the same method call but in a different context.

As far as I can tell there isn't currently a way around this, but it's tough to say because of the lack of packaged app documentation. Since the alternative to this is not having links work at all for the majority of users, I'm going to close this as by design.

**Closed by trjast** 2016-05-18 01:39 UTC
